name: Node.js CI/CD to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Upgrade npm
      run: npm install -g npm

    - name: Install server dependencies
      run: npm ci
      working-directory: ./server

    - name: Install client dependencies
      run: npm ci
      working-directory: ./client

    - name: Build server
      run: npm run build --if-present
      working-directory: ./server

    - name: Test server
      run: npm test
      working-directory: ./server

    - name: Archive server code for deployment
      run: zip -r server.zip .
      working-directory: ./server

    - name: Deploy server to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: beworking_app
        environment_name: Beworkingapp-env
        version_label: ${{ github.run_number }}
        region: eu-west-1
        source_bundle: server.zip
      working-directory: ./server
