name: Deploy to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p /home/ubuntu/beworking_app/client
          mkdir -p /home/ubuntu/beworking_app/server
          cd /home/ubuntu/beworking_app/client
          git pull origin main
          npm install
          npm run build
          pm2 restart all
          cd /home/ubuntu/beworking_app/server
          git pull origin main
          npm install
          npm run build
          pm2 restart all