name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install client dependencies and build
      run: |
        cd client
        npm install
        npm run build

    - name: Transfer client files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "client/build"
        target: "/home/ubuntu/beworking_app/client"

    - name: Install server dependencies
      run: |
        cd ../server
        npm install

    - name: Transfer server files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "server"
        target: "/home/ubuntu/beworking_app/server"